Liquibase extension for YugabyteDB
yugabyte/liquibase-yugabytedb pull request #1
Opened 2021-07-05 14:26 UTC by Sfurti-yb

# Liquibase extension for YugabyteDB

## Run Tests

1. Start a YugabyteDB cluster.
   
    ```<YUGABYTEDB_INSTALL_DIR>/bin/yb-ctl start```
2. Run the [yugabytedb-init.sql](src/test/resources/docker/yugabytedb-init.sql) file via ysqlsh.
3. Update the configuration in [harness-config.yml](src/test/resources/harness-config.yml).
4. Run the command:
    
    ```mvn clean install```

2021-07-13 05:50 UTC, kneeraj commented
Please write some details about the change. Why this extension required? Some important changes should be mentioned.

2021-07-13 05:51 UTC, kneeraj approved these changes
LGTM. Minor changes and needs more information in the PR summary.

2021-07-13 05:51 UTC, kneeraj commented on .github/workflows/pull-request-labeled-release.yml
> +        java: [ 8, 11, 16 ]
Just revert this file. Seems no change.

2021-07-13 07:11 UTC, ashetkar approved these changes
LGTM with minor suggestions. I understand we'll have to further update the README later anyway.

2021-07-13 07:11 UTC, ashetkar commented on README.md
> +2. Run the [yugabytedb-init.sql](src/test/resources/docker/yugabytedb-init.sql) file via ysqlsh.
For #2, we can also provide the command to do it like this:
```
<YUGABYTEDB_INSTALL_DIR>/bin/ysqlsh -f <path/to/yugabytedb-init.sql>
```

2021-07-13 07:11 UTC, ashetkar commented on README.md
> +3. Update the configuration in [harness-config.yml](src/test/resources/harness-config.yml).
nit: "Update the connection details in ..." would be clearer, I think (I know I wrote this point :) ).

2021-07-13 07:11 UTC, ashetkar commented on .github/workflows/pull-request.yml
> +        run: mvn test
Is this change required?

2021-07-14 05:16 UTC, kneeraj commented
Hi Sfurti and Amogh ... We do support "initially deferrable" clause. Please remove the override that returns "false" in the YugabyteDBDatabase implementation.

2021-07-14 05:17 UTC, kneeraj requested changes
Hi Sfurti and Amogh ... We do support "initially deferrable" clause. Please remove the override that returns "false" in the YugabyteDBDatabase implementation.

2021-07-14 06:33 UTC, kneeraj approved these changes
Ignore the last comment as "Initially deferrable" clause is supported only for Foreign Keys  and not Unique Key Constraints.

2021-07-19 14:57 UTC, merged